
templates:
  tv:
    regexp:
      reject:
        - "9JKL"
        - "^Babylon"
        - "AIW: Go For Broke"
        - "Apocalypse.Code.The.Bible.Prediction"
        - "Baskets"
        - "Beirut to Bosnia"
        - "Castle Builders"
        - "Class Act"
        - "complete"
        - "DC's Legends of Tomorrow"
        - "Defying Gravity : The Untold Story of Women’s Gymnastics"
        - "Discovery Realtime Sun Sea and Bargain Spotting"
        - "Drunk History UK"
        - "Dug Days"
        - "Easy Japanese"
        - "farsi"
        - "flemish"
        - "Francis Brennan's Grand Vietnamese Tour"
        - "Gotham Comedy Live"
        - "Greek"
        - "Haustyrann"
        - "High School Musical: The Musical: The Series"
        - "Hootenanny"
        - "italian"
        - "Lacheys Bar"
        - "Legends of Tomorrow"
        - "Married At First Sight"
        - "Married To Medicine"
        - "Married to Real Estate"
        - "Motherland: Fort Salem"
        - "Norwegian Rednecks Camping"
        - "Oprah Behind The Scenes"
        - "s01-02"
        - "s01-03"
        - "s02-03"
        - "s1-s2"
        - "s1-s3"
        - "s2-s3"
        - "Sampled"
        - "season"
        - "Serbia Old and New"
        - "spanish"
        - "The Champions"
        - "The Curse of Oak Island"
        - "The Great Canadian Baking Show"
        - "The Great Food Truck Race"
        - "The Great Pottery Throw Down"
        - "The Turkish Detective"
        - "uin.15"
        - "Uncle from Another World"
        - "Uncle Grandpa"
        - "Undercover Boss"
        - "Undercover High"
        - "Undercover In Nederland"
        - "White Collar Brawlers"

    series:
      settings:
        group 720i-1080p:
          exact: yes
          season_packs: no
          upgrade: no
      720i-1080p:
        - "A Spy Among Friends"
        - "Abbott Elementary"
        - "The Afterparty"
        - "Aftertaste"
        - "Am I Being Unreasonable"
        - "Anxious People"
        - "Archer (2009)"
        - "Around the World in 80 Days (2021)"
        - "The Artful Dodger"
        - "B Positive"
        - "Back to Life"
        - "Bad Sisters"
        - "Band of Brothers"
        - "Barry"
        - "Based on a True Story"
        - "The Bear"
        - "Better Off Ted"
        - "The Big Door Prize"
        - "Black Mirror"
        - "Black Monday"
        - "Bless This Mess"
        - "Bob Hearts Abishola"
        - "Bob's Burgers"
        - "Boiling Point (2023)"
        - "The Book Group"
        - "Bosch: Legacy"
        - "Brassic"
        - "Broadchurch"
        - "Buffering"
        - "Bupkis"
        - "Call Me Kat"
        - "Catastrophe (2015)"
        - "Cheaters (2022)"
        - "Chivalry"
        - "Chloe"
        - "Class of '07"
        - "The Cleaner (2021)"
        - "Code 404"
        - "Colin from Accounts"
        - "Comedians in Cars Getting Coffee"
        - "Con Man"
        - "The Control Room"
        - "Counterpart"
        - "Criminal: United Kingdom"
        - "Crossing Lines"
        - "Cunk on Earth"
        - "Daisy Jones & The Six"
        - "Dark Winds"
        - "Dead Boss"
        - "Dead Pixels"
        - "Dead Set"
        - "Dead to Me"
        - "Deadloch"
        - "Deadwater Fell"
        - "Delicious"
        - "The Delivery Man"
        - "Detectorists"
        - "Dickensian"
        - "Disjointed"
        - "Documentary Now!"
        - "Drunk History"
        - "The Durrells"
        - "The End of the F***ing World"
        - "The English"
        - "Everyone Else Burns"
        - "Everything's Gonna Be Okay"
        - "Extraordinary"
        - "Family Guy"
        - "The Fast Show"
        - "Finding Alice"
        - "Fisk"
        - "Five Bedrooms"
        - "Fleishman Is in Trouble"
        - "The Flight Attendant"
        - "Florida Girls"
        - "Flowers"
        - "Frank of Ireland"
        - "Free Agents"
        - "Fresh Meat"
        - "Full Circle (2023)"
        - "GameFace"
        - "Gentleman Jack"
        - "Get Shorty"
        - "Ghosted"
        - "Ghosts (2019)"
        - "Ghosts (US)"
        - "The Girl Before"
        - "Girlboss"
        - "Glitch (2015)"
        - "God's Favorite Idiot"
        - "The Gold"
        - "Goliath"
        - "Good Grief (2021)"
        - "Good Omens"
        - "Grace and Frankie"
        - "Gracepoint"
        - "The Great"
        - "Great Expectations (2023)"
        - "Ground Floor"
        - "Guilt (2019)"
        - "Hacks (2021)"
        - "Hang Ups"
        - "Happy Valley"
        - "Harlan Coben's Shelter"
        - "Harley Quinn"
        - "Harrow"
        - "Heading Out"
        - "Heartbreak High (2022)"
        - "Heartburn Hotel"
        - "Hebburn"
        - "Hello Tomorrow!"
        - "Henpocalypse!"
        - "Here We Go (2022)"
        - "High Desert"
        - "Him & Her"
        - "History of the World, Part II"
        - "Hitmen"
        - "Hold the Sunset"
        - "Homecoming"
        - "Homecoming (2018)"
        - "House of Lies"
        - "How To with John Wilson"
        - "Hunderby"
        - "I Am Not Okay With This"
        - "I Hate You"
        - "I Love That for You"
        - "I Think You Should Leave with Tim Robinson"
        - "I Want My Wife Back"
        - "I'm a Virgo"
        - "Idiotsitter"
        - "Imposters"
        - "The Inbetweeners"
        - "Inside Amy Schumer"
        - "Inside Man (2022)"
        - "Inside No. 9"
        - "Intelligence (2020)"
        - "Inventing Anna"
        - "It's Always Sunny in Philadelphia"
        - "The Jewish Enquirer"
        - "Joe Pera Talks with You"
        - "Justified"
        - "Justified: City Primeval"
        - "Kaleidoscope (2023)"
        - "Kate & Koji"
        - "Kevin Can F**k Himself"
        - "Killing Eve"
        - "Killing It"
        - "Laid"
        - "Landscapers"
        - "Last Tango in Halifax"
        - "Liar"
        - "The Librarians (2014)"
        - "Life & Beth"
        - "Little Britain USA"
        - "Living with Yourself"
        - "Los Espookys"
        - "Loudermilk"
        - "Love"
        - "Love Life"
        - "Love Life (2020)"
        - "Lucky Hank"
        - "The Madame Blanc Mysteries"
        - "Made For Love"
        - "Magpie Murders"
        - "Mammals"
        - "Man Stroke Woman"
        - "Mandy"
        - "Maniac (2018)"
        - "Maron"
        - "Master of None"
        - "The Mick"
        - "Miracle Workers (2019)"
        - "Modern Love"
        - "The Moodys"
        - "The Moodys (US)"
        - "The Morning Show"
        - "Mr Inbetween"
        - "Mrs. Davis"
        - "Mrs. Fletcher"
        - "Murder City"
        - "My Boys"
        - "My Brilliant Friend"
        - "Nathan Barley"
        - "The Neighborhood"
        - "Never Have I Ever"
        - "Newsreaders"
        - "The Night Manager"
        - "Nine Perfect Strangers"
        - "No Offence"
        - "Normal People"
        - "Now Apocalypse"
        - "The Old Man"
        - "One Night (2023)"
        - "Only Murders in the Building"
        - "The Orville"
        - "The Other One (2020)"
        - "The Other Two"
        - "Our Flag Means Death"
        - "The Outlaws"
        - "Ozark"
        - "Parade's End"
        - "Parks and Recreation"
        - "Party Down"
        - "Patrick Melrose"
        - "Peacemaker"
        - "Peaky Blinders"
        - "People of Earth"
        - "Perry Mason (2020)"
        - "Peter Kay's Car Share"
        - "Pivoting"
        - "Please Like Me"
        - "Poker Face (2023)"
        - "The Politician"
        - "The Power of Parker"
        - "Powerless"
        - "Psychobitches"
        - "Pulling"
        - "Rain Dogs"
        - "Ramy"
        - "The Real O'Neals"
        - "Reboot (2022)"
        - "Reginald the Vampire"
        - "Reno 911!"
        - "Reservation Dogs"
        - "Resident Advisors"
        - "Resident Alien"
        - "The Resort"
        - "Rick and Morty"
        - "The Righteous Gemstones"
        - "Rosehaven"
        - "Russian Doll"
        - "Santa Clarita Diet"
        - "Schitt's Creek"
        - "Scott & Bailey"
        - "Severance"
        - "Sex Education"
        - "The Sex Lives of College Girls"
        - "Shakespeare & Hathaway - Private Investigators"
        - "Shakespeare And Hathaway"
        - "Shining Vale"
        - "Shrink"
        - "Shrinking"
        - "Siblings"
        - "Sick Note"
        - "Silicon Valley (2013)"
        - "The Sinner"
        - "Slip"
        - "Slow Horses"
        - "Smiling Friends"
        - "So Help Me Todd"
        - "Somebody Somewhere"
        - "Somewhere Boy"
        - "South Park"
        - "The South Westerlies"
        - "Space Force"
        - "Splitting Up Together"
        - "Sprung"
        - "Staged"
        - "Starstruck"
        - "State of the Union"
        - "Stath Lets Flats"
        - "Still Up"
        - "The Strange World of Gurney Slade"
        - "Strike"
        - "Stuck (2022)"
        - "Such Brave Girls"
        - "Sunnyside"
        - "Ted Lasso"
        - "Ten Percent"
        - "This Fool"
        - "This Way Up"
        - "The Time Traveler's Wife"
        - "Timewasters"
        - "Tiny Beautiful Things"
        - "Toast"
        - "Toast of America"
        - "Toast of Tinseltown"
        - "Tokyo Vice"
        - "Trial & Error"
        - "The Trip"
        - "Trying"
        - "The Tuckers"
        - "Turn of the Tide"
        - "Two Pints of Lager and a Packet of Crisps"
        - "Uncle"
        - "Unforgotten"
        - "The Unicorn"
        - "United States of Al"
        - "Unprisoned"
        - "Upload"
        - "Upright"
        - "Urban Myths"
        - "Vice Principals"
        - "WandaVision"
        - "Wannabe"
        - "Wedding Season"
        - "Weird Loners"
        - "Welcome to Flatch"
        - "What We Do in the Shadows"
        - "The White Lotus"
        - "White Van Man (2011)"
        - "Whites"
        - "Why Didn't They Ask Evans"
        - "Why Women Kill"
        - "Will & Grace"
        - "The Witchfinder"
        - "Witless"
        - "Wolf Like Me"
        - "The Woman in the House Across the Street from the Girl in the Window"
        - "Workaholics"
        - "Workin' Moms"
        - "The Worst Week of My Life"
        - "Wrecked (2016)"
        - "The Wrong Mans"
        - "Yellowjackets"
        - "You"
        - "You're the Worst"
        - "The Young Offenders"

    transmission:
      username: xobtlu
      password: "90-BNMoiuxcv"
      port: 12010

schedules:
  - tasks: '*'
    interval:
      minutes: 15

tasks:
  ipt:
    rss: https://iptorrents.com/t.rss?u=1961978;tp=44462d6cdc795cb9204c454f38785dcd;78;23;24;25;66;82;65;83;79;22;5;99;4;download;new
    template: tv
    content_size:
      min: 12
      max: 2000
      strict: no

  tl:
    rss: https://rss24h.torrentleech.org/23b3105eda2478749d21
    template: tv
    content_size:
      min: 12
      max: 2000
      strict: no
